### ISSUE TITLE
tmt: automatically determine copr version matrix

### ISSUE THREAD

**Issue by kwk** [fedora-llvm-team/llvm-snapshots#79]
In the [tmt workflow](https://github.com/kwk/llvm-daily-fedora-rpms/blob/main/.github/workflows/tmt.yml) we have a fixed matrix:

```yaml
jobs:
  tmt:
    strategy:
      matrix:
        os: [fedora]
        version: [37, 38, 39, rawhide]
```

It would be cool if we could utilize [the following function](https://github.com/kwk/llvm-daily-fedora-rpms/blob/eb347defe4d25eb4844ce6a6d8c2b533d2d185b1/github/functions.sh#L43-L46) to feed the `version` of the matrix in the workflow file:

```bash
# Prints the chroots we care about.
function get_chroots() {
  copr list-chroots | grep -P '^fedora-(rawhide|[0-9]+)' | tr '\n' ' '
}
```

One needs to [explore this](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#example-using-contexts-to-create-matrices) in the documentation. 

This relates to: #59
